### ISSUE TITLE
use it

### ISSUE THREAD

**Issue by momomo316** [KangSinWon/sensor_fusion#1]
Hello, can you teach me how to use it

**Comment by KangSinWon** [comment]
I'm updating it as I learn.
For now, you can view the visualization code via ipynb/kitti_utils.ipynb.

**Comment by Shinwon-Kang** [comment]
I'm updating it as I learn.
For now, you can view the visualization code via ipynb/kitti_utils.ipynb.

**Comment by momomo316** [comment]
Thank you for the response.
